/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/activity": {
    get: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.activity.created_at"];
          name?: parameters["rowFilter.activity.name"];
          picture_url?: parameters["rowFilter.activity.picture_url"];
          id?: parameters["rowFilter.activity.id"];
          seasons?: parameters["rowFilter.activity.seasons"];
          location?: parameters["rowFilter.activity.location"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["activity"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** activity */
          activity?: definitions["activity"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.activity.created_at"];
          name?: parameters["rowFilter.activity.name"];
          picture_url?: parameters["rowFilter.activity.picture_url"];
          id?: parameters["rowFilter.activity.id"];
          seasons?: parameters["rowFilter.activity.seasons"];
          location?: parameters["rowFilter.activity.location"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.activity.created_at"];
          name?: parameters["rowFilter.activity.name"];
          picture_url?: parameters["rowFilter.activity.picture_url"];
          id?: parameters["rowFilter.activity.id"];
          seasons?: parameters["rowFilter.activity.seasons"];
          location?: parameters["rowFilter.activity.location"];
        };
        body: {
          /** activity */
          activity?: definitions["activity"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  activity: {
    created_at?: string;
    name: {
      en: string,
      fr: string
    };
    picture_url?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    seasons: unknown[];
    location: unknown[];
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** activity */
  "body.activity": definitions["activity"];
  "rowFilter.activity.created_at": string;
  "rowFilter.activity.name": string;
  "rowFilter.activity.picture_url": string;
  "rowFilter.activity.id": string;
  "rowFilter.activity.seasons": string;
  "rowFilter.activity.location": string;
}

export interface operations { }

export interface external { }
